In [1]:
#역전파 알고리즘을 위한 벡터 개념
import numpy as np
X=np.array([1,2,3,4])

In [3]:
np.ndim(X) #ndim:차원확인 => 1차원배열

X.shape #원소가 4개인 1차원

(4,)

In [4]:
X=np.array([[1,2],[3,4],[5,6]])
np.ndim(X)

2

In [7]:
X=np.array([[1,2],[3,4]])
Y=np.array([[5,6],[7,8]])

#행렬의 곱(내적) XY
print(np.dot(X,Y))
print(np.dot(Y,X)) #벡터의 내적 성립X

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]



## 역전파 원리 

In [11]:
X=np.array([1.0,0.5])
W1=np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]]) #2by3

B1=np.array([0.1,0.2,0.3]) #bias

print(np.dot(X,W1)+B1)

def sigmoid(x):
    return 1 / (1+np.exp(-x))

H1=np.dot(X,W1)+B1
Z1=sigmoid(H1)

[0.3 0.7 1.1]


In [14]:
W2=np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2= np.array([0.1,0.2])

H2=np.dot(Z1,W2)+B2
Z2=sigmoid(H2)
print(Z2)

[0.62624937 0.7710107 ]


In [17]:
W3=np.array([[0.1,0.2],[0.2,0.3]])
B3= np.array([0.1,0.2])

H3=np.dot(Z2,W3)+B3
print(H3)

#Neuran Network의 분류/예측을 결정하는 것은 마지막 레이어의 어떤 활성함수를 쓰느냐에 따라 달라진다.
#다분류를 한다면 softmax, 이진분류: sigmoid(0에서 1사이)

[0.31682708 0.55655308]


## softmax 함수

In [21]:
score=np.array([20,10,1])
exp_s=np.exp(score) #지수함수

In [22]:
sum_exp_s= np.sum(exp_s)
y=exp_s/sum_exp_s
y

array([9.99954597e-01, 4.53978684e-05, 5.60254205e-09])