## 토큰화 +코사인 유사도 Cosine Similarity 

In [2]:
import nltk
nltk.__version__

'3.4.5'

In [4]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [5]:
import konlpy

In [15]:
#토큰화 : 단어, 어절 , 문장, 문단
#문장을 단어 단위로 나누는 작업
from nltk.tokenize import word_tokenize #표쥰(일반)

word_tokenize("Mr.Jone's Don't be")

['Mr.Jone', "'s", 'Do', "n't", 'be']

In [14]:
from nltk.tokenize import WordPunctTokenizer

print(WordPunctTokenizer().tokenize("Mr.Jone's Don't be"))

['Mr', '.', 'Jone', "'", 's', 'Don', "'", 't', 'be']


In [22]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

print(text_to_word_sequence("Mr.Jone's Don't be")) #모두 소문자로 변환, 느낌표, 마침표 제거된다.

['mr', "jone's", "don't", 'be']


In [21]:
from nltk.tokenize import TreebankWordTokenizer

twt= TreebankWordTokenizer()
print(twt.tokenize("Mr.Jone's Don't be"))

['Mr.Jone', "'s", 'Do', "n't", 'be']


In [23]:
text="Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects."

In [26]:
print(sent_tokenize(text))

['Python is an interpreted, high-level, general-purpose programming language.', "Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace.", 'Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.']


In [27]:
#토큰화 과정에서 단어가 어떤 품사로 쓰였는지 품사 태깅(Tagging)

text="Python is an interpreted, high-level, general-purpose programming language."
print(word_tokenize(text))

['Python', 'is', 'an', 'interpreted', ',', 'high-level', ',', 'general-purpose', 'programming', 'language', '.']


In [28]:
from nltk.tag import pos_tag

In [29]:
pos_tag(word_tokenize(text))

[('Python', 'NNP'),
 ('is', 'VBZ'),
 ('an', 'DT'),
 ('interpreted', 'JJ'),
 (',', ','),
 ('high-level', 'JJ'),
 (',', ','),
 ('general-purpose', 'JJ'),
 ('programming', 'NN'),
 ('language', 'NN'),
 ('.', '.')]

In [30]:
#형태소 분석기: Okt, Mecab ..
from konlpy.tag import Okt

In [32]:
okt=Okt()
print(okt.morphs("오늘은 수요일, 내일은 목요일 입니다."))
print(okt.pos("오늘은 수요일, 내일은 목요일 입니다."))
print(okt.nouns("오늘은 수요일, 내일은 목요일 입니다."))

['오늘', '은', '수요일', ',', '내일', '은', '목요일', '입니다', '.']
[('오늘', 'Noun'), ('은', 'Josa'), ('수요일', 'Noun'), (',', 'Punctuation'), ('내일', 'Noun'), ('은', 'Josa'), ('목요일', 'Noun'), ('입니다', 'Adjective'), ('.', 'Punctuation')]
['오늘', '수요일', '내일', '목요일']


In [33]:
#코사인 유사도 
#cos(d1,d2)=(d1*d2)


In [36]:
import numpy as np
A=np.array([[0,0,0,1,0,1,1,0,0],
          [0,0,0,1,1,0,1,0,0],
          [0,1,1,0,2,0,0,0,0],
          [1,0,0,0,0,0,0,1,1]])
np.shape(A)

(4, 9)

In [66]:
U, s, VT=np.linalg.svd(A,full_matrices=True) #full SVD, truncated SVD

In [67]:
U.shape

(4, 4)

In [68]:
U.round(2) #직교행렬(4*4)

array([[-0.24,  0.75,  0.  , -0.62],
       [-0.51,  0.44, -0.  ,  0.74],
       [-0.83, -0.49, -0.  , -0.27],
       [-0.  , -0.  ,  1.  ,  0.  ]])

In [ ]:
S=np.zeros((4,9))
S[:4,:4]=np.diag(s)
print(S.round(2)) #특이값 행렬

In [ ]:
print(VT.round(2))

In [69]:
np.zeros((4,9))
np.diag(s)

array([[2.68731789, 0.        , 0.        , 0.        ],
       [0.        , 2.04508425, 0.        , 0.        ],
       [0.        , 0.        , 1.73205081, 0.        ],
       [0.        , 0.        , 0.        , 0.77197992]])

In [ ]:
#절단된(truncated) SVD
#토픽 2개
S=S[:2,:2]
print(S.round(2))

In [70]:
U.shape  # 4by4
U=U[:,:2] # 4by2
U.round(2)

array([[-0.24,  0.75],
       [-0.51,  0.44],
       [-0.83, -0.49],
       [-0.  , -0.  ]])

In [ ]:
VT.shape #(9,9)
VT=VT[:2,:] #(2,9) 토픽*단어개수
#VT의 각 열은 잠재 의미를 나타내기 위한 수치화된
#단어 벡터

VT.round(2)
#U*S*VT != A

In [71]:
VT=VT[:2,:] # (2by9)
#VT의 각 열은 잠재 의미를 나타내는 수치 의미
VT.round(2)

array([[-0.  , -0.31, -0.31, -0.28, -0.8 , -0.09, -0.28, -0.  , -0.  ],
       [ 0.  , -0.24, -0.24,  0.58, -0.26,  0.37,  0.58, -0.  , -0.  ]])

In [ ]:
Aprime=np.dot(np.dot(U,S),VT)
print(Aprime.round(2))
print(A)

### DTM 

In [ ]:
"""
        돈  사람  저는  좋아요
줄거리1  0   1     1     1
줄거리2  1   0     1     1
줄거리3  2   0     2     2
"""

In [73]:
from numpy.linalg import norm
mov1=np.array([0,1,1,1])
mov2=np.array([1,0,1,1])
mov3=np.array([2,0,2,2])

In [76]:
#코사인 유사도
#np.dot(mov1,mov2)/(norm(mov1)*norm(mov2))
#np.dot(mov1,mov2) #두 벡터의 내적


def cos_sim(X,Y):
    return np.dot(X,Y)/(norm(X)*norm(Y))

2

In [ ]:
print(cos_sim(mov1,mov2))
print(cos_sim(mov2,mov3))
print(cos_sim(mov1,mov3))

In [80]:
import pandas as pd

In [100]:
data=pd.read_csv("movies_metadata.csv")

In [101]:
data["overview"].isnull().sum()
data["overview"]=data["overview"].fillna("")

In [102]:
data["overview"]

0        Led by Woody, Andy's toys live happily in his ...
1        When siblings Judy and Peter discover an encha...
2        A family wedding reignites the ancient feud be...
3        Cheated on, mistreated and stepped on, the wom...
4        Just when George Banks has recovered from his ...
                               ...                        
45461          Rising and falling between a man and woman.
45462    An artist struggles to finish his work while a...
45463    When one of her hits goes wrong, a professiona...
45464    In a small town live two brothers, one a minis...
45465    50 years after decriminalisation of homosexual...
Name: overview, Length: 45466, dtype: object

In [103]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [104]:
tfidf=TfidfVectorizer(stop_words="english")
tfidf_mat=tfidf.fit_transform(data["overview"])

In [106]:
tfidf_mat.shape

(45466, 75827)

In [ ]:
#Toy story와 가장 코사인 유사도가 큰 영화 10편 추출
