# Text Translation (텍스트 번역)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('fra-eng/fra.txt', sep = '\t', names=['eng','fra',' '])
df = df.iloc[:70000,:2]

In [3]:
df.sample(20)

eng                                  fra
47940    I like being on my own.              J'apprécie d'être seul.
2162                I didn't go.            Je ne m'y suis pas rendu.
65199  What do you really think?             Que penses-tu vraiment ?
63681  Take as long as you need.  Prends le temps dont tu as besoin !
16267          The doors opened.              Les portes s'ouvrirent.
55151   I wanted to read a book.            Je voulais lire un livre.
22458         You're very funny.             Vous êtes très marrants.
7800             I don't gamble.                      Je ne joue pas.
44118     They're in the shower.           Elles sont dans la douche.
27435        You were bad at it.             Ça ne vous a pas réussi.
35819      I'd like to be alone.               J'aimerais être seule.
29363       I just want answers.      Je veux seulement des réponses.
19486         I was just mugged.            Je viens d'être dévalisé.
44676     We have no complaints.  Nous n'enregistrons aucune plainte.
20235         Message me online.      Envoie-moi un message en ligne.
10129           Did he go there?                      Y est-il allé ?
62191  I'd like to learn French.    J'aimerais apprendre le français.
30598       Let the party begin.                Que la fête commence.
45747     You're worse than Tom.                  Tu es pire que Tom.
59279  Are you planning to stay?            Prévoyez-vous de rester ?

In [4]:
df['fra'] = "\t " + df['fra'].values +" \n"
# df['fra']=df['fra'].apply(lambda x:'\t '+x+' \n')

In [5]:
df['fra']

0                                          \t Va ! \n
1                                       \t Salut ! \n
2                                        \t Salut. \n
3                                       \t Cours ! \n
4                                      \t Courez ! \n
                             ...                     
69995         \t Je ne suis jamais monté à cheval. \n
69996    \t Je ne suis jamais monté sur un cheval. \n
69997               \t Je n'ai jamais vu Tom ivre. \n
69998          \t Je n'ai jamais vu d'arc-en-ciel. \n
69999                \t Je ne t’ai jamais vu rire. \n
Name: fra, Length: 70000, dtype: object

In [6]:
df['eng']

0                               Go.
1                               Hi.
2                               Hi.
3                              Run!
4                              Run!
                    ...            
69995    I've never ridden a horse.
69996    I've never ridden a horse.
69997    I've never seen Tom drunk.
69998    I've never seen a rainbow.
69999    I've never seen you laugh.
Name: eng, Length: 70000, dtype: object

In [7]:
engVocab = set()
fraVocab = set()

In [8]:
for line in df.eng:
    for c in line:
        engVocab.add(c)

In [9]:
engVocab

{' ',
 '!',
 '"',
 '$',
 '%',
 '&',
 "'",
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 'ç',
 'é',
 '’',
 '€'}

In [10]:
for line in df.fra:
    for c in line:
        fraVocab.add(c)

In [11]:
engVocabsize = len(engVocab) + 1
fraVocabsize = len(fraVocab) + 1
print(engVocabsize)
print(fraVocabsize)

80
106


In [12]:
engVocab = sorted(list(engVocab))
fraVocab = sorted(list(fraVocab))

In [13]:
engVocab

[' ',
 '!',
 '"',
 '$',
 '%',
 '&',
 "'",
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 'ç',
 'é',
 '’',
 '€']

In [14]:
engToIndex = dict((c,i+1) for i,c in enumerate(engVocab))
fraToIndex = dict((c,i+1) for i,c in enumerate(fraVocab))

In [15]:
engToIndex

{' ': 1,
 '!': 2,
 '"': 3,
 '$': 4,
 '%': 5,
 '&': 6,
 "'": 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '/': 11,
 '0': 12,
 '1': 13,
 '2': 14,
 '3': 15,
 '4': 16,
 '5': 17,
 '6': 18,
 '7': 19,
 '8': 20,
 '9': 21,
 ':': 22,
 '?': 23,
 'A': 24,
 'B': 25,
 'C': 26,
 'D': 27,
 'E': 28,
 'F': 29,
 'G': 30,
 'H': 31,
 'I': 32,
 'J': 33,
 'K': 34,
 'L': 35,
 'M': 36,
 'N': 37,
 'O': 38,
 'P': 39,
 'Q': 40,
 'R': 41,
 'S': 42,
 'T': 43,
 'U': 44,
 'V': 45,
 'W': 46,
 'X': 47,
 'Y': 48,
 'Z': 49,
 'a': 50,
 'b': 51,
 'c': 52,
 'd': 53,
 'e': 54,
 'f': 55,
 'g': 56,
 'h': 57,
 'i': 58,
 'j': 59,
 'k': 60,
 'l': 61,
 'm': 62,
 'n': 63,
 'o': 64,
 'p': 65,
 'q': 66,
 'r': 67,
 's': 68,
 't': 69,
 'u': 70,
 'v': 71,
 'w': 72,
 'x': 73,
 'y': 74,
 'z': 75,
 'ç': 76,
 'é': 77,
 '’': 78,
 '€': 79}

In [16]:
#영어 문장 인코딩
encoderInput = []
for li in df.eng:
    t = []
    for c in li :
         t.append(engToIndex[c])
    encoderInput.append(t)      
print(len(encoderInput))
print(encoderInput[:10])

70000
[[30, 64, 10], [31, 58, 10], [31, 58, 10], [41, 70, 63, 2], [41, 70, 63, 2], [46, 57, 64, 23], [46, 64, 72, 2], [29, 58, 67, 54, 2], [31, 54, 61, 65, 2], [33, 70, 62, 65, 10]]


In [17]:
#프랑스 문장 인코딩
decoderInput = []
for li in df.fra:
    t = []
    for c in li :
         t.append(fraToIndex[c])
    decoderInput.append(t)      
print(decoderInput[:10])

[[1, 3, 48, 53, 3, 4, 3, 2], [1, 3, 45, 53, 64, 73, 72, 3, 4, 3, 2], [1, 3, 45, 53, 64, 73, 72, 14, 3, 2], [1, 3, 29, 67, 73, 70, 71, 105, 4, 3, 2], [1, 3, 29, 67, 73, 70, 57, 78, 105, 4, 3, 2], [1, 3, 43, 73, 61, 3, 26, 3, 2], [1, 3, 83, 53, 3, 53, 64, 67, 70, 71, 105, 4, 3, 2], [1, 3, 27, 73, 3, 58, 57, 73, 3, 4, 3, 2], [1, 3, 82, 3, 64, 9, 53, 61, 56, 57, 105, 4, 3, 2], [1, 3, 45, 53, 73, 72, 57, 14, 3, 2]]


In [18]:
#프랑스 문장 인코딩
decoderFra = []
for li in df.fra:
    t = []
    i = 0
    for c in li :
        if i > 0:
             t.append(fraToIndex[c])
        i = i+1
    decoderFra.append(t)      
print(decoderFra[:10])

[[3, 48, 53, 3, 4, 3, 2], [3, 45, 53, 64, 73, 72, 3, 4, 3, 2], [3, 45, 53, 64, 73, 72, 14, 3, 2], [3, 29, 67, 73, 70, 71, 105, 4, 3, 2], [3, 29, 67, 73, 70, 57, 78, 105, 4, 3, 2], [3, 43, 73, 61, 3, 26, 3, 2], [3, 83, 53, 3, 53, 64, 67, 70, 71, 105, 4, 3, 2], [3, 27, 73, 3, 58, 57, 73, 3, 4, 3, 2], [3, 82, 3, 64, 9, 53, 61, 56, 57, 105, 4, 3, 2], [3, 45, 53, 73, 72, 57, 14, 3, 2]]


In [19]:
#문장의 길이로 통일 #[3,9,,,15]
maxEngLen = max([len(li) for li in df.eng])
maxFraLen = max([len(li) for li in df.fra]) 

In [20]:
from keras.preprocessing.sequence import pad_sequences

Using TensorFlow backend.


In [21]:
encoderInput = pad_sequences(encoderInput, maxlen = maxEngLen, padding = 'post')
decoderInput = pad_sequences(decoderInput, maxlen = maxFraLen, padding = 'post')

In [22]:
decoderFra = pad_sequences(decoderFra, maxlen = maxFraLen, padding = 'post')

In [23]:
encoderInput

array([[30, 64, 10, ...,  0,  0,  0],
       [31, 58, 10, ...,  0,  0,  0],
       [31, 58, 10, ...,  0,  0,  0],
       ...,
       [32,  7, 71, ..., 63, 60, 10],
       [32,  7, 71, ..., 64, 72, 10],
       [32,  7, 71, ..., 56, 57, 10]])

In [24]:
import numpy as np
np.shape(encoderInput)
np.shape(decoderInput)

(70000, 76)

In [25]:
print(decoderInput)

[[ 1  3 48 ...  0  0  0]
 [ 1  3 45 ...  0  0  0]
 [ 1  3 45 ...  0  0  0]
 ...
 [ 1  3 36 ...  0  0  0]
 [ 1  3 36 ...  0  0  0]
 [ 1  3 36 ...  0  0  0]]


In [26]:
from keras.utils import to_categorical #인코더 Input, 디코더 Input/ Output

encoderInput = to_categorical(encoderInput)
decoderInput = to_categorical(decoderInput)
decoderFra = to_categorical(decoderFra)

In [27]:
np.shape(encoderInput) #(70000줄, 최대 글자수(한 줄당), 글자의 종류)
np.shape(decoderInput)

(70000, 76, 106)

In [28]:
#training시 이전 상태의 실제값을 현재 상태의 decoder 입력으로 해야한다.
from keras.layers import Input, Embedding, Dense, LSTM
from keras.models import Model

In [29]:
"""
ex) input = Input(shape=(50,1))
feature : 1ro, time-staml(시점): 50개(50갸싹)
LSTM(출력)(input)
d1 = Dense(10, activation = 'relu')(It)
d2 = Dense(1, activation = 'sigmoid')(d1)
Model(inputs = ip, outputs=d2)

"""


In [30]:
#Input(shape=(50,1))
decoderInputs = Input(shape=(None,fraVocabsize))
#디코더입력 = Input(time-step, 프랑스어 문자 종류 수)
encoderInputs = Input(shape=(None,engVocabsize))
# 인코더입력 = Input( , 영어 문자 종류 수)

# 인코더 LSTM 셀|
encoderLSTM = LSTM(units=256, return_state=True)
# LSTM(출력수=256, return_state=인코더의 마지막 상태 정보를 디코더의 입력 상태 정보로 전달하기 위한 옵션, )

# 디코더 LSTM 셀
decoderLSTM = LSTM(units=256, return_sequences=True, return_state=True)

# 인코더 LSTM 셀의 입력 정의
_, stateH, stateC = encoderLSTM(encoderInputs)
# _, hidden_state, cell 상태
# 위로 출력 => stateH, 다른 셀로 전달 stateC

encoderStates = [stateH, stateC]
# encoderStates : 컨텍스트 벡터

decoderOutputs, _, _ = decoderLSTM(decoderInputs, initial_state=encoderStates)
# 셀의 관한 상태 정보는 decoder에서는 필요가 없다.
decoderSoftmax = Dense(fraVocabsize, activation='softmax')
decoderOutputs = decoderSoftmax(decoderOutputs)

model = Model(inputs = [encoderInputs,decoderInputs], outputs=decoderOutputs)
model.compile(optimizer = 'rmsprop',loss='categorical_crossentropy')
model.fit(x = [encoderInput, decoderInput], y = decoderFra, batch_size=64, epochs=50, validation_split=0.2)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Train on 56000 samples, validate on 14000 samples
Epoch 1/50
56000/56000 [==============================] - 280s 5ms/step - loss: 0.7532 - val_loss: 0.6812
Epoch 2/50
56000/56000 [==============================] - 279s 5ms/step - loss: 0.4688 - val_loss: 0.5466
Epoch 3/50
56000/56000 [==============================] - 278s 5ms/step - loss: 0.3911 - val_loss: 0.4859
Epoch 4/50
56000/56000 [==============================] - 279s 5ms/step - loss: 0.3489 - val_loss: 0.4494
Epoch 5/50
56000/56000 [==============================] - 278s 5ms/step - loss: 0.3214 - val_loss: 0.4253
Epoch 6/50
56000/56000 [==============================] - 279s 5ms/step - loss: 0.3015 - val_loss: 0.4081
Epoch 7/50
56000/56000 [==============================] - 279s 5ms/step - loss: 0.2861 - val_loss: 0.3963
Epoch 8/50
56000/56000 [========

In [31]:
from keras.models import load_model

model.save('translation_eng_to_fra.h5')

In [112]:
"""
seq2seq동작

1) 입력 문장 -> 인코더 -> 은닉상태, 셀상태
2) 상태정보와 start 시글널('\t') 을 디코더로 전달
3) 다음 문자를 예측 (stop 시그널 '\n'이 등장할 때까지 반복)
"""

"\nseq2seq동작\n\n1) 입력 문장 -> 인코더 -> 은닉상태, 셀상태\n2) 상태정보와 start 시글널('\t') 을 디코더로 전달\n3) 다음 문자를 예측 (stop 시그널 '\n'이 등장할 때까지 반복)\n"

In [117]:
encoderModel = Model(inputs=encoderInputs, outputs=encoderStates)

#디코더
decoderStateInputHidden = Input(shape=(256,))
decoderStateInputCell= Input(shape=(256,))
decoderStateInputs = [decoderStateInputHidden, decoderStateInputCell]
decoderOutputs, stateHidden, stateCell = decoderLSTM(decoderInputs, initial_state = decoderStateInputs)
decoderStates = [stateHidden, stateCell]

decoderOutputs = decoderSoftmax(decoderOutputs)
decoderModel = Model(inputs=[decoderInputs]+decoderStateInputs, outputs=[decoderOutputs]+decoderStates)

In [118]:
indexToEng = dict((i,c) for c,i in engToIndex.items())
indexToFra = dict((i,c) for c,i in fraToIndex.items())

In [121]:
def decodeSeq(inputSeq): # (1, 26, 80)
    
    statesValue = encoderModel.predict(inputSeq)
    # print(statesValue)
    # print(np.shape(statesValue))
    
    targetSeq = np.zeros((1,1,fraVocabsize)) # 1,1,106
    targetSeq[0,0,fraToIndex['\t']] = 1 # 원핫인코딩
    
    stop = False
    decodedSent=""
    while not stop: # "\n"문자를 만날때까지 반복
        
        output, h, c = decoderModel.predict([targetSeq]+statesValue)
        # 예측값을 프랑스 문자로 변환
        tokenIndex = np.argmax(output[0,-1,:]) 
        predChar = indexToFra[tokenIndex]
        
        # 현시점 예측문자가 예측문장에 추가
        decodedSent+=predChar
        
        if (predChar=="\n" or len(decodedSent)>maxFraLen):
            stop = True
            
        # 현시점 예측결과가 다음 시점에 입력으로 
        targetSeq = np.zeros((1,1,fraVocabsize))
        targetSeq[0,0,tokenIndex] = 1
        
        # 현시점 상태를 다음 시점 상태로 사용
        statesValue = [h,c]
    
    return decodedSent # 번역결과

In [122]:
for seqIndex in [1,50,100,200,300]:
    
    inputSeq = encoderInput[seqIndex:seqIndex+1]
    # print(np.shape(inputSeq)) # (1, 26, 80)
    decodedSeq = decodeSeq(inputSeq)
    
    print("입력문장:", df.eng[seqIndex])
    print("정답:", df.fra[seqIndex][1:len(df.fra[seqIndex])-1]) # "\t", "\n" 제거
    print("번역기:", decodedSeq[:len(decodedSeq)-1])
    print("\n")

입력문장: Hi.
정답:  Salut ! 
번역기:  Salut ! 


입력문장: I lied.
정답:  J'ai menti. 
번역기:  J'ai manqué. 


입력문장: Come in.
정답:  Entre. 
번역기:  Entrez ! 


입력문장: Skip it.
정답:  Pas grave. 
번역기:  Contrôle-lui. 


입력문장: I did OK.
정답:  Je m'en suis bien sortie. 
번역기:  Je me suis amusé. 




# Text Generation ( 텍스트 생성 ) 

In [36]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [54]:
text = """과수원에 있는 배가 맛있다
그의 배는 많이 나왔다
가는 길에 배를 탔고 오는 길에도 배를 탔다"""

In [55]:
t = Tokenizer()
t.fit_on_texts([text])

In [103]:
t.word_index

{'배를': 1,
 '과수원에': 2,
 '있는': 3,
 '배가': 4,
 '맛있다': 5,
 '그의': 6,
 '배는': 7,
 '많이': 8,
 '나왔다': 9,
 '가는': 10,
 '길에': 11,
 '탔고': 12,
 '오는': 13,
 '길에도': 14,
 '탔다': 15}

In [56]:
vocSize = len(t.word_index)+1 #안덱스 1~15

In [60]:
seqs = list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        seq = encoded[:i+1]
        seqs.append(seq)

In [61]:
seqs

[[2, 3],
 [2, 3, 4],
 [2, 3, 4, 5],
 [6, 7],
 [6, 7, 8],
 [6, 7, 8, 9],
 [10, 11],
 [10, 11, 1],
 [10, 11, 1, 12],
 [10, 11, 1, 12, 13],
 [10, 11, 1, 12, 13, 14],
 [10, 11, 1, 12, 13, 14, 1],
 [10, 11, 1, 12, 13, 14, 1, 15]]

In [66]:
maxlen = max(len(i) for i in seqs)

In [67]:
seqs = pad_sequences(seqs, maxlen = maxlen, padding = 'pre')

In [68]:
seqs

array([[ 0,  0,  0,  0,  0,  0,  2,  3],
       [ 0,  0,  0,  0,  0,  2,  3,  4],
       [ 0,  0,  0,  0,  2,  3,  4,  5],
       [ 0,  0,  0,  0,  0,  0,  6,  7],
       [ 0,  0,  0,  0,  0,  6,  7,  8],
       [ 0,  0,  0,  0,  6,  7,  8,  9],
       [ 0,  0,  0,  0,  0,  0, 10, 11],
       [ 0,  0,  0,  0,  0, 10, 11,  1],
       [ 0,  0,  0,  0, 10, 11,  1, 12],
       [ 0,  0,  0, 10, 11,  1, 12, 13],
       [ 0,  0, 10, 11,  1, 12, 13, 14],
       [ 0, 10, 11,  1, 12, 13, 14,  1],
       [10, 11,  1, 12, 13, 14,  1, 15]])

In [70]:
seqs = np.array(seqs)
x = seqs[:,:-1]
y = seqs[:,-1]

In [73]:
y = to_categorical(y, num_classes=vocSize)

In [89]:
maxlen

8

In [74]:
y

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
      dtype=float32)

In [105]:
from keras.models import Sequential
from keras.layers import SimpleRNN
model = Sequential()
model.add(Embedding(vocSize, 10, input_length=maxlen-1)) #입력차원, 출력차원 : 최대길이-1
model.add(SimpleRNN(32)) #단어의 임베딩 벡터가 10차원,  32개 히든 상태 
model.add(Dense(vocSize, activation = 'softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [109]:
model.fit(x,y,epochs=200)

Epoch 1/200
13/13 [==============================] - 0s 24ms/step - loss: 2.7568 - accuracy: 0.0769
Epoch 2/200
13/13 [==============================] - 0s 458us/step - loss: 2.7498 - accuracy: 0.0769
Epoch 3/200
13/13 [==============================] - 0s 384us/step - loss: 2.7416 - accuracy: 0.2308
Epoch 4/200
13/13 [==============================] - 0s 461us/step - loss: 2.7328 - accuracy: 0.2308
Epoch 5/200
13/13 [==============================] - 0s 230us/step - loss: 2.7235 - accuracy: 0.2308
Epoch 6/200
13/13 [==============================] - 0s 154us/step - loss: 2.7138 - accuracy: 0.1538
Epoch 7/200
13/13 [==============================] - 0s 154us/step - loss: 2.7038 - accuracy: 0.2308
Epoch 8/200
13/13 [==============================] - 0s 231us/step - loss: 2.6933 - accuracy: 0.2308
Epoch 9/200
13/13 [==============================] - 0s 154us/step - loss: 2.6823 - accuracy: 0.2308
Epoch 10/200
13/13 [==============================] - 0s 231us/step - loss: 2.6710 - accurac

Epoch 82/200
13/13 [==============================] - 0s 231us/step - loss: 1.2138 - accuracy: 0.8462
Epoch 83/200
13/13 [==============================] - 0s 77us/step - loss: 1.1936 - accuracy: 0.8462
Epoch 84/200
13/13 [==============================] - 0s 154us/step - loss: 1.1735 - accuracy: 0.9231
Epoch 85/200
13/13 [==============================] - 0s 154us/step - loss: 1.1534 - accuracy: 0.9231
Epoch 86/200
13/13 [==============================] - 0s 153us/step - loss: 1.1335 - accuracy: 0.9231
Epoch 87/200
13/13 [==============================] - 0s 231us/step - loss: 1.1138 - accuracy: 0.9231
Epoch 88/200
13/13 [==============================] - 0s 154us/step - loss: 1.0941 - accuracy: 0.9231
Epoch 89/200
13/13 [==============================] - 0s 154us/step - loss: 1.0747 - accuracy: 0.9231
Epoch 90/200
13/13 [==============================] - 0s 153us/step - loss: 1.0553 - accuracy: 0.9231
Epoch 91/200
13/13 [==============================] - 0s 154us/step - loss: 1.0362 

Epoch 162/200
13/13 [==============================] - 0s 231us/step - loss: 0.2635 - accuracy: 1.0000
Epoch 163/200
13/13 [==============================] - 0s 154us/step - loss: 0.2591 - accuracy: 1.0000
Epoch 164/200
13/13 [==============================] - 0s 231us/step - loss: 0.2549 - accuracy: 1.0000
Epoch 165/200
13/13 [==============================] - 0s 231us/step - loss: 0.2507 - accuracy: 1.0000
Epoch 166/200
13/13 [==============================] - 0s 154us/step - loss: 0.2467 - accuracy: 1.0000
Epoch 167/200
13/13 [==============================] - 0s 154us/step - loss: 0.2427 - accuracy: 1.0000
Epoch 168/200
13/13 [==============================] - 0s 153us/step - loss: 0.2388 - accuracy: 1.0000
Epoch 169/200
13/13 [==============================] - 0s 154us/step - loss: 0.2350 - accuracy: 1.0000
Epoch 170/200
13/13 [==============================] - 0s 154us/step - loss: 0.2312 - accuracy: 1.0000
Epoch 171/200
13/13 [==============================] - 0s 154us/step - lo

In [106]:
t.word_index.items()

dict_items([('배를', 1), ('과수원에', 2), ('있는', 3), ('배가', 4), ('맛있다', 5), ('그의', 6), ('배는', 7), ('많이', 8), ('나왔다', 9), ('가는', 10), ('길에', 11), ('탔고', 12), ('오는', 13), ('길에도', 14), ('탔다', 15)])

In [110]:
def sentGen(model, t, word, n): #모델, 토크나이져, 입력단어, 예측단어갯수
    sent = ""
    word2 = word
    for _ in range(n): #3번 반복
        encoded = t.texts_to_sequences([word])[0] #과수원에 
        encoded = pad_sequences([encoded], maxlen = 7, padding='pre')
        res = model.predict_classes(encoded)
        
        for w,i in t.word_index.items():
            if i == res: #예측 단어와 인덱스가 동일한 단어
                break
        word = word + " " + w #"과수원에 있는"(새 단어)
        sent = sent+ " " + w
    print(word2 + sent)

In [111]:
sentGen(model, t, '과수원에', 3) #과수원에 뒤에 등장하는 3개 단어 예측

과수원에 있는 배가 맛있다


#  