In [ ]:
1. NumPy를 사용하여 다음과 같은 행렬을 만든다.

10 20 30 40
50 60 70 80

In [7]:
import numpy as np

data=np.array([[10,20,30,40],[50,60,70,80]])
data

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
2. 다음 행렬과 같은 행렬이 있다.

m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
이 행렬에서 값 7 을 인덱싱한다.
이 행렬에서 값 14 을 인덱싱한다.
이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [117]:
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
m[1,2] #이 행렬에서 값 7 을 인덱싱한다.
m[2,-1] #이 행렬에서 값 14 을 인덱싱한다.
m[1,[1,2]] #이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[[1,2],[2,2]] #이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[0:2,3:5] #이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

array([[3, 4],
       [8, 9]])

In [ ]:
3.다음 행렬과 같은 배열이 있다.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
이 배열에서 3의 배수를 찾아라.
이 배열에서 4로 나누면 1이 남는 수를 찾아라.
이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [37]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#3-1)이 배열에서 3의 배수를 찾아라.
for i in x-1:
    if x[i]%3==0:
        print(x[i])
        


3
6
9
12
15
18


In [38]:
#3-2)이 배열에서 4로 나누면 1이 남는 수를 찾아라.

for i in x-1:
    if x[i]%4==1:
        print(x[i])

1
5
9
13
17


In [39]:
#3-3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

for i in x-1:
    if x[i]%3==0 and x[i]%4==1 :
        print(x[i])

9


In [ ]:
4. 타이타닉 데이터셋에서 Age , sibsp, parch, fare 컬럼에 대해 표준화 하시오.
-누락값에 대해서는 Age열은 평균 나이로 대체,
-sibsp는 최대값으로 대체
-parch는 최소값으로 대체
-fare는 평균 요금으로 대체

In [40]:
import pandas as pd

In [109]:
df=pd.read_csv("train .csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [140]:
#numpy로 표준화
titanic_age=df.loc[:,"Age"]
df["Age"]=df["Age"].fillna(np.mean(titanic_age))
std_a=(df.Age-np.mean(df.Age,axis=0))/np.std(df.Age,axis=0)
std_a

0     -5.924806e-01
1      6.387890e-01
2     -2.846632e-01
3      4.079260e-01
4      4.079260e-01
           ...     
886   -2.077088e-01
887   -8.233437e-01
888    4.374348e-15
889   -2.846632e-01
890    1.770629e-01
Name: Age, Length: 891, dtype: float64

In [130]:
#scipy 로 표준화
import scipy.stats as ss

std_ss=ss.zscore(df["Age"])
std_ss


array([-0.5924806 ,  0.63878901, -0.2846632 ,  0.40792596,  0.40792596,
        0.        ,  1.87005862, -2.13156761, -0.20770885, -1.20811541,
       -1.97765891,  2.17787603, -0.7463893 ,  0.71574336, -1.20811541,
        1.94701297, -2.13156761,  0.        ,  0.10010856,  0.        ,
        0.40792596,  0.33097161, -1.13116105, -0.1307545 , -1.66984151,
        0.63878901,  0.        , -0.82334365,  0.        ,  0.        ,
        0.79269771,  0.        ,  0.        ,  2.79351083, -0.1307545 ,
        0.94660642,  0.        , -0.66943495, -0.900298  , -1.20811541,
        0.79269771, -0.20770885,  0.        , -2.05461326, -0.82334365,
        0.        ,  0.        ,  0.        ,  0.        , -0.900298  ,
       -1.74679586, -0.66943495,  1.48528687, -0.05380014,  2.71655648,
        0.        , -0.66943495, -0.09227732, -1.90070456, -1.43897846,
       -0.5924806 ,  0.63878901,  1.17746947, -1.97765891,  0.        ,
        0.        , -0.05380014, -0.82334365, -0.97725235, -0.28

In [156]:
#sklearn 으로 표준화
import numpy as np
from sklearn.preprocessing import *
import matplotlib.pyplot as plt

arr1=np.array(df.Age)
ss_age=StandardScaler().fit_transform(arr1.reshape(-1,1))
ss_age

array([[-0.5924806 ],
       [ 0.63878901],
       [-0.2846632 ],
       [ 0.40792596],
       [ 0.40792596],
       [ 0.        ],
       [ 1.87005862],
       [-2.13156761],
       [-0.20770885],
       [-1.20811541],
       [-1.97765891],
       [ 2.17787603],
       [-0.7463893 ],
       [ 0.71574336],
       [-1.20811541],
       [ 1.94701297],
       [-2.13156761],
       [ 0.        ],
       [ 0.10010856],
       [ 0.        ],
       [ 0.40792596],
       [ 0.33097161],
       [-1.13116105],
       [-0.1307545 ],
       [-1.66984151],
       [ 0.63878901],
       [ 0.        ],
       [-0.82334365],
       [ 0.        ],
       [ 0.        ],
       [ 0.79269771],
       [ 0.        ],
       [ 0.        ],
       [ 2.79351083],
       [-0.1307545 ],
       [ 0.94660642],
       [ 0.        ],
       [-0.66943495],
       [-0.900298  ],
       [-1.20811541],
       [ 0.79269771],
       [-0.20770885],
       [ 0.        ],
       [-2.05461326],
       [-0.82334365],
       [ 0

In [122]:
#numpy로 표준화
titanic_ss=df.loc[:,"SibSp"]
df["SibSp"]=df["SibSp"].fillna(np.max(titanic_ss))
df_ss=(df.SibSp-np.mean(df.SibSp))/np.std(df.SibSp)
df_ss

0      0.432793
1      0.432793
2     -0.474545
3      0.432793
4     -0.474545
         ...   
886   -0.474545
887   -0.474545
888    0.432793
889   -0.474545
890   -0.474545
Name: SibSp, Length: 891, dtype: float64

In [138]:
#numpy로 표준화

titanic_p=df.loc[:,"Parch"]
df["Parch"]=df["Parch"].fillna(np.min(titanic_p))
df_p=(df.Parch-np.mean(df.Parch))/np.std(df.Parch)
df_p

0     -0.473674
1     -0.473674
2     -0.473674
3     -0.473674
4     -0.473674
         ...   
886   -0.473674
887   -0.473674
888    2.008933
889   -0.473674
890   -0.473674
Name: Parch, Length: 891, dtype: float64

In [141]:
#numpy로 표준화

titanic_f=df.loc[:,"Fare"]
df["Fare"]=df["Fare"].fillna(np.mean(titanic_f))
df_f=(df.Fare-np.mean(df.Fare))/np.std(df.Fare)
df_f

0     -0.502445
1      0.786845
2     -0.488854
3      0.420730
4     -0.486337
         ...   
886   -0.386671
887   -0.044381
888   -0.176263
889   -0.044381
890   -0.492378
Name: Fare, Length: 891, dtype: float64