In [ ]:
문제 1.
길이가 10인 0-벡터를 만드세요.

In [2]:
import numpy as np

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
문제 2.
길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [5]:
Vec1=np.zeros(10)
Vec1[4]=1
Vec1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
문제 3.
10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [12]:
Vec2=np.arange(10,50)
Vec2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
문제 4.
위 벡터의 순서를 바꾸세요.

In [17]:
np.array(sorted(Vec2, reverse=True))

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [ ]:
문제 5.
0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [19]:
Vec3=np.arange(0,9).reshape(3,3)
Vec3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
문제 6.
벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [21]:
Vec4=np.array([1,2,0,0,4,0])
Vec4[Vec4!=0]

array([1, 2, 4])

In [ ]:
문제 7.
3x3 단위 행렬(identity matrix)을 만드세요

In [22]:
Vec5=np.eye(3)
Vec5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
문제 8.
난수 원소를 가지는 3x3 행렬을 만드세요

In [26]:
Vec6=np.random.randn(3,3)
Vec6

array([[-1.24739857, -0.05884786, -0.17818837],
       [-0.68254052,  0.97973213, -0.17573917],
       [ 0.90612393, -0.42191682,  0.98310111]])

In [ ]:
문제 9.
위에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.

In [27]:
Vec6.min()  #최소
Vec6.max()  #최대

-1.247398566767232

In [ ]:
문제 10.
위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [40]:
print(Vec6.mean(axis=0))  #행평균
print(Vec6.mean(axis=1)) #열평균

[-0.34127172  0.16632248  0.20972452]
[-0.4948116   0.04048415  0.48910274]


In [ ]:
문제 11.
4개의 직사각형이 평면에 있는데 밑변이 모두 가로축에 평행하다. 이 직사각형들이 차지하는 면적을 구하는 프로그램을 작성하시오. 
이 네 개의 직사각형들은 서로 떨어져 있을 수도 있고 겹쳐 있을 수도 있다.
또한 하나가 다른 하나를 포함할 수도 있으며, 변이나 꼭지점이 겹쳐질 수도 있다.

입력형식

하나의 직사각형은 왼쪽 아래의 꼭지점과 오른쪽 위의 꼭지점의 좌표로 주어진다.
입력은 네 줄이며, 각 줄은 네 개의 정수로 하나의 직사각형을 나타낸다. 
첫 번째와 두 번째의 정수는 사각형의 왼쪽 아래 꼭지점의 x좌표, y좌표이고, 세 번째와 네 번째의 정수는
사각형의 오른쪽 위 꼭지점의 x좌표, y좌표이다. 단, x좌표와 y좌표는 1 이상이고 1000 이하인 정수이다.

출력형식

화면에 4개의 직사각형이 차지하는 면적을 출력한다.

입력예제

1 2 4 4
2 3 5 7
3 1 6 5
7 3 8 6

출력예제

26

In [69]:
Sq_num=np.array([1, 2, 4 ,4 ,2, 3 ,5 ,7 ,3, 1, 6 ,5 ,7 ,3, 8 ,6]).reshape(4,4)
x=[]
y=[]

for i in range(len(Sq_num)):
    for j in range(0,len(Sq_num),2):
        x.append(Sq_num[i][j])
        y.append(Sq_num[i][j+1])
    
    #ga=x[i+1]-x[i]
    #se=y[i+1]-y[i]



        



        


   

    
    
    
    

[1, 4, 2, 5, 3, 6, 7, 8]
