In [5]:
#배열 축 추가

import numpy as np

a=np.array([1,2,3,4])
a.shape

(4,)

In [7]:
a41=a[np.newaxis,:]
a41      

array([[1, 2, 3, 4]])

In [13]:
b=np.arange(15).reshape(3,5)
b351=b[:,:,np.newaxis]
b351.shape


b315=b[:,np.newaxis,:]
b315

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [18]:
a=np.array([0,1,2,3])
a8=np.tile(a,2)
a8

a32=np.tile(a,(3,2))
a32


b=np.arange(8).reshape(2,4)
b28=np.tile(b,2)
b28


b44=np.tile(b,(2,1))
b44

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
#행렬의 내적 : aT*a
a=np.arange(15).reshape(3,5)
a.T

np.transpose(a)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [25]:
a=np.arange(10)
ai=a[0:5]
ai[1:3]=10
ai  
a   #a도 함께 변환

array([ 0, 10, 10,  3,  4,  5,  6,  7,  8,  9])

In [32]:
arr=np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [33]:
abc=np.array(["a","a","b","c","c"])
abc

array(['a', 'a', 'b', 'c', 'c'], dtype='<U1')

In [38]:
arr[abc=="a"]
arr[abc=="a",:2]


arr[abc!="a"]
arr[~(abc=="a")]


arr[(abc=="a")|(abc=="b")]
arr[(abc!="a")&(abc!="b")]

arr[abc=="a"]=99
arr

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [41]:
arr[arr>20]=0
arr

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
arr[(arr>=8) & (arr<=15)]=10
arr

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [16, 17, 18, 19]])

In [46]:
#around:반올림
a=np.array([-3.5, -2.2, 0, 1.6])
np.around(a) #반올림
np.round(a,1) #소수 이하 첫째짜리 
np.rint(a) #가까운 정수로 올림 또는 내림
np.fix(a) #0방향으로 가까운 정수로 올림 또는 내림
np.ceil(a) #값보다 크거나 같은 가장 작은 정수값으로 올림
np.floor(a) #값보다 작거나 같은 가장 큰 정수값으로 내림

array([-4., -3.,  0.,  1.])

In [53]:
a=np.array([1,2,3,4])
c=np.arange(1,5).reshape(2,2)
c

array([[1, 2],
       [3, 4]])

In [55]:
#배열간의 곱셈

np.prod(c) #24
np.prod(c,axis=0) #열 곱셈
np.prod(c,axis=1) #행 곱셈

np.sum(a, keepdims=True) # 모든 차원애 대한 덧셈


array([10])

In [60]:
d=np.array([[1,2],[3,np.nan]])
d

array([[ 1.,  2.],
       [ 3., nan]])

In [59]:
#np.nanprod:곱셈할때 nan을 1로 간주해서 연산
np.nanprod(d, axis=0)

array([3., 2.])

In [61]:
#np.nansum: 덧셈연산을 할때 nan을 0으로 간주
np.nansum(d, axis=0)

array([4., 2.])

In [67]:
#np.cumprod: 누적곱
b=np.arange(1,7).reshape(2,3)
np.cumprod(b) 
np.cumprod(b, axis=0) 

array([[ 1,  2,  3],
       [ 4, 10, 18]], dtype=int32)

In [70]:
#밑이 자연상수 e인 지수함수로 변환

x=np.array([0.00001,1,2,10])

np.exp(x)
np.log(x)
np.log2(x)
np.log10(x)

array([-5.     ,  0.     ,  0.30103,  1.     ])

## bikesharing(Day23 참고) 이어서----                            